### ISSUE TITLE
As a user, I want to be able to view multiple passages from an assortment of public-domain books, so that I choose a passage to generate an image from.

### ISSUE THREAD

**Issue by chrishollandaise** [chrishollandaise/book-cover-generator#1]
# Acceptance Criteria
- [ ] Given a user visits our website
- [ ] When the website loads and is populated
- [ ] Then a user should see a gallery of books to choose from
- [ ] Then a user should be able to click on the books and be given a random passage from that book to choose from

# Estimation of Work 
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
What is not known? Potential roadblocks?

# Notes
- The gallery should display the book cover and the name of the book. For ideas for the UI, please consult some of these [Dribbble designs](https://dribbble.com/search/gallery).
- The passages should be descriptive, and ideally describe scenes or characters from the book.
