### ISSUE TITLE
As a front-end developer, I want to be able to click a button to generate an illustration from a passage, so I can visualize a scene.

### ISSUE THREAD

**Issue by chrishollandaise** [chrishollandaise/book-cover-generator#2]
# Acceptance Criteria
- [ ] Given a user has chosen a book, passage, and art style
- [ ] When the user clicks on the generate button
- [ ] Then the user should be able to wait and see the generated illustration next to their passage
- [ ] Then the user should be able to retry the generation

# Estimation of Work 
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
What is not known? Potential roadblocks?

# Notes
- This component should be able to conditional render. In other words, if the user is waiting they should see a waiting screen.
