### ISSUE TITLE
As a user, I want to be able to choose an art style before generating an image, so that I can see a variety of illustrations

### ISSUE THREAD

**Issue by chrishollandaise** [chrishollandaise/book-cover-generator#3]
# Acceptance Criteria
- [ ] Given a user has clicked on a book
- [ ] When the user is done selecting a passage
- [ ] Then the user should be able to select a single art style from a radio button list

# Estimation of Work 
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
What is not known? Potential roadblocks?

# Notes
- There needs to be at least 3 art styles but no more than 5 for the MVP. If you need help with art styles to choose from, please visit this link: [https://magazine.artland.com/art-movements-and-styles/](https://magazine.artland.com/art-movements-and-styles/)
- If you are not familiar with what a radio button list is, please refer to the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio).
- The user should be able to select the art style once and be able to switch to other passages without clicking on the radio button list again. In other words, it is not a per-passage component, but rather part of the book component.
