### ISSUE TITLE
As a front-end developer, I want to be able to access an RESTful API so that I can display books and passages to the users

### ISSUE THREAD

**Issue by chrishollandaise** [chrishollandaise/book-cover-generator#4]
# Acceptance Criteria
- [ ] Given a request for books/passages is made from the web app
- [ ] When the request is considered not corrupted and valid (AKA 200)
- [ ] Then the API should respond by returning a JSON array of books, meta information, and chosen passages

The schema of this types in the JSON should validate correctly to these types: 
> ! means should not be null, please refer to syntax of [GraphQL schemas](https://graphql.org/learn/schema/)
```gql
type Book {
title: String!
author: String
genre: String
metadata: Meta!
passages: [Passage!]!
}

type Passage {
page: Int!
text: String!
}

type Meta { 
lang: String!
source: String!
}
```

**Example of JSON output:** 
```json
{
  "result": [
    {
      "title": "Pride and Prejudice",
      "author": "Jane Austen",
      "genre": "Fiction",
      "metadata": {
        "lang": "English",
        "source": "https://www.gutenberg.org/ebooks/1342"
      },
      "passages": [
        {
          "page": 29,
          "text": "On entering the drawing-room she found the whole party at loo, and was immediately invited to join them; but suspecting them to be playing high she declined it, and making her sister the excuse, said she would amuse herself for the short time she could stay below, with a book. Mr. Hurst looked at her with astonishment."
        },
        {
          "page": 111,
          "text": "Mrs. Bennet, to whose apartment they all repaired, after a few minutes’ conversation together, received them exactly as might be expected; with tears and lamentations of regret, invectives against the villainous conduct of Wickham, and complaints of her own sufferings and ill-usage; blaming everybody but the person to whose ill-judging indulgence the errors of her daughter must principally be owing"
        }
      ]
    }
  ]
}
```
# Estimation of Work 
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
- Be sure to be consistent with the source you derive your page numbers from. If you use Gutenberg, always choose the same source.

# Notes
- Currently for the MVP, these can be stored as a single JSON with at least 5 books, this is what the API will return to the web application
- For the `genre` or `lang` fields in the schema definition, be consistent with the capitalization and convention. Please document this somewhere for other developers to reference. For languages, take a look at [IETF language tags](https://www.wikiwand.com/en/IETF_language_tag) or a [list of genres from Wikipedia](https://www.wikiwand.com/en/List_of_genres)
